bezwaarschriften:
  input:
    folder: input
  extractie:
    max-concurrent: 3
    max-pogingen: 3
    mock:
      min-delay-seconden: 5
      max-delay-seconden: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bezwaarschriften
    username: bezwaarschriften_user
    password: bezwaarschriften_password
  autoconfigure:
    # prevent lookup of keycloak URL on Bamboo
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    config:
      enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          omgeving:
            client-secret: '{noop}secret'

management:
  health:
    elasticsearch:
      enabled: false

kc:
  realm: Omgeving
  base-url: https://ssov2-ontwikkel.omgeving.vlaanderen.be/auth
  internal-base-url: http://keycloak-on.lb.cumuli.be:8080/auth


eureka:
  client:
    enabled: false

cumuli:
  security:
    enable:
      mock: true
    users:
      - username: bezwaarschriftenSpringBootAdmin
        password: "{noop}bezwaarschriftenSpringBootAdmin"
        roles:
          - BezwaarschriftenSpringBootAdmin
      - username: gebruiker
        password: "{noop}gebruiker"
        roles:
          - BezwaarschriftenGebruiker
    systemuser:
      name: bezwaarschriften
      password: "{noop}bezwaarschriften"

logging:
  file:
    path: "./target"
